name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Create Artifacts
        run: tar -czf release-package.tar.gz -C dist .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-package
          path: release-package.tar.gz

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  publish-github:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-package

      - name: Publish to GitHub Packages
        run: npm publish release-package.tar.gz --registry ${{secrets.GITHUB_PACKAGES_REGISTRY_URL}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: publish-github
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-package

      - name: Publish to npm
        run: npm publish release-package.tar.gz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
